<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jiehui Kwa">
<meta name="dcterms.date" content="2023-03-20">
<meta name="description" content="The Happiness Data Project">

<title>kjhblog - Final Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">kjhblog</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../about.html">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Final Project</h1>
                  <div>
        <div class="description">
          The Happiness Data Project
        </div>
      </div>
                </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Jiehui Kwa </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">March 20, 2023</p>
      </div>
    </div>
    
      <div>
      <div class="quarto-title-meta-heading">Modified</div>
      <div class="quarto-title-meta-contents">
        <p class="date-modified">March 20, 2023</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="the-data-of-happiness" class="level1">
<h1>The Data of Happiness</h1>
<section id="by-jiehui-kwa-3202023" class="level4">
<h4 class="anchored" data-anchor-id="by-jiehui-kwa-3202023">by Jiehui Kwa, 3/20/2023</h4>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<section id="project-description" class="level3">
<h3 class="anchored" data-anchor-id="project-description">Project Description</h3>
<p>The data I will be analyzing in my final project was gathered from the World Happiness Report (by the Gallup World Survey), which seeks to measure and make more concrete what has always been a very subjective and abstract, yet an infinitely integral aspect of human life – happiness.</p>
<p><strong>Data:</strong> <a href="https://www.kaggle.com/datasets/jahaidulislam/world-happiness-report-2005-2021">World Happiness Reports from 2005-2021</a></p>
<p>Happiness is something that all humans crave and desire. From Aristotle who espoused a eudaimonic and virtue-driven happiness, to Epicurus who advocated for hedonism and embracing feelings of pleasure, philosophers have long discussed and debated what happiness entails, and how we as humans can seek to achieve it. Nonetheless, it remains as enigmatic and relevant as ever, with mental health awareness on the rise and nascent fields like positive psychology dedicated to the study of happiness. In a way, it seems like there has been little to no progress made in the past centuries on how we can go about achieving this ever-elusive goal. Yet, perhaps it was this very sense of abstruseness that has driven my lifelong fascination with happiness, well-being, and the factors that influence it.</p>
<p>The question then arises – how can I approach a topic so abstract and nuanced, when it has even stumped humankind for centuries? Well, I believe the answer to that is, data. By looking at happiness through the lens of data, I hope to uncover and analyze patterns in happiness around the world, and hopefully gain a deeper insight into what affects happiness.</p>
</section>
<section id="research-questions" class="level3">
<h3 class="anchored" data-anchor-id="research-questions">Research Questions</h3>
<ol type="1">
<li><p>How do economic factors affect happiness?</p></li>
<li><p>How does one’s social environment affect happiness?</p></li>
</ol>
</section>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<p>The World Happiness Report data that I have used for this project was preprocessed, synthesized, and published by Jahaidul Islam on kaggle. First, I downloaded and imported the csv file as a pandas dataframe, which will later allow me to manipulate and analyze the data.</p>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>hp_df <span class="op">=</span> pd.read_csv(<span class="st">'https://raw.githubusercontent.com/kjh97/DH-140/main/data/World%20Happiness%20Report%202005-2021.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, I sorted the data according to the Happiness Score as it was previously sorted by country name.</p>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>hp_df.sort_values(<span class="st">"Happiness Score"</span>, ascending <span class="op">=</span> <span class="va">False</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>hp_df.set_index(<span class="st">'Country'</span>, inplace<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="how-to-measure-happiness" class="level3">
<h3 class="anchored" data-anchor-id="how-to-measure-happiness">How to measure happiness?</h3>
<p><strong>The six values measured in the World Happiness Report:</strong></p>
<ul>
<li><p>real GDP per capita</p></li>
<li><p>social support</p></li>
<li><p>healthy life expectancy</p></li>
<li><p>freedom to make life choices</p></li>
<li><p>generosity</p></li>
<li><p>perceptions of corruption</p></li>
</ul>
<section id="cleaning-data" class="level4">
<h4 class="anchored" data-anchor-id="cleaning-data">Cleaning data</h4>
<p>In the main dataframe of World Happiness Report data from 2005 to 2021, I removed the “Confidence in national government”, “Positive affect”, and “Negative affect” columns since they will not be utilized in my analysis.</p>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">del</span> hp_df[<span class="st">'Positive affect'</span>] </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="kw">del</span> hp_df[<span class="st">'Negative affect'</span>] </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Fig 1:</strong> Summary description of statistics provided in dataframe</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>hp_df.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Year</th>
      <th>Happiness Score</th>
      <th>Log GDP per capita</th>
      <th>Social support</th>
      <th>Life expectancy</th>
      <th>Freedom</th>
      <th>Generosity</th>
      <th>Perceptions of corruption</th>
      <th>Confidence in national government</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>count</th>
      <td>2089.000000</td>
      <td>2089.000000</td>
      <td>2063.000000</td>
      <td>2076.000000</td>
      <td>2031.000000</td>
      <td>2057.000000</td>
      <td>2009.000000</td>
      <td>1976.000000</td>
      <td>1873.000000</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>2013.727621</td>
      <td>5.473747</td>
      <td>9.377592</td>
      <td>0.811542</td>
      <td>63.180326</td>
      <td>0.745462</td>
      <td>0.000102</td>
      <td>0.746474</td>
      <td>0.483914</td>
    </tr>
    <tr>
      <th>std</th>
      <td>4.455614</td>
      <td>1.115567</td>
      <td>1.143843</td>
      <td>0.118935</td>
      <td>6.948546</td>
      <td>0.140751</td>
      <td>0.161082</td>
      <td>0.186136</td>
      <td>0.191515</td>
    </tr>
    <tr>
      <th>min</th>
      <td>2005.000000</td>
      <td>2.178809</td>
      <td>5.526723</td>
      <td>0.290184</td>
      <td>6.720000</td>
      <td>0.257534</td>
      <td>-0.335739</td>
      <td>0.035198</td>
      <td>0.068769</td>
    </tr>
    <tr>
      <th>25%</th>
      <td>2010.000000</td>
      <td>4.651972</td>
      <td>8.471678</td>
      <td>0.747664</td>
      <td>58.965000</td>
      <td>0.651689</td>
      <td>-0.113172</td>
      <td>0.689840</td>
      <td>0.334808</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>2014.000000</td>
      <td>5.405246</td>
      <td>9.462799</td>
      <td>0.834770</td>
      <td>64.980003</td>
      <td>0.767357</td>
      <td>-0.023366</td>
      <td>0.801339</td>
      <td>0.467046</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>2017.000000</td>
      <td>6.294282</td>
      <td>10.347391</td>
      <td>0.904682</td>
      <td>68.362499</td>
      <td>0.857677</td>
      <td>0.090584</td>
      <td>0.870789</td>
      <td>0.616302</td>
    </tr>
    <tr>
      <th>max</th>
      <td>2021.000000</td>
      <td>8.018934</td>
      <td>11.665803</td>
      <td>0.987343</td>
      <td>74.349998</td>
      <td>0.985178</td>
      <td>0.706377</td>
      <td>0.983276</td>
      <td>0.993604</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>Fig 1 provides a statistical summary of the different metrics that can be found in the data, such as ‘Social support’ and ‘Life expectancy’, which are factors that influence the ‘Happiness Score’. The ‘Happiness Score’ refers to the average happiness rating assigned to a country based on a self-report well-being assessment known as the <strong>Cantril Ladder</strong>, which measures well-being on a scale of 1 to 10.</p>
<p><strong>Cantril Ladder:</strong> <em>“Please imagine a ladder with steps numbered from zero at the bottom to 10 at the top. The top of the ladder represents the best possible life for you and the bottom of the ladder represents the worst possible life for you. On which step of the ladder would you say you personally feel you stand at this time? On which step do you think you will stand about five years from now?”</em></p>
</section>
</section>
<section id="grouping-and-organizing-data" class="level3">
<h3 class="anchored" data-anchor-id="grouping-and-organizing-data">Grouping and organizing data</h3>
<p>I created another dataframe that provided me with the 2021 World Happiness Report data (latest available data from the dataset), in order to help me analyze and visualize the latest data on happiness. Also, I removed the “Year” column as it is no longer relevant.</p>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>hp21_df <span class="op">=</span> hp_df[hp_df[<span class="st">'Year'</span>]<span class="op">==</span><span class="dv">2021</span>]</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="kw">del</span> hp21_df[<span class="st">'Year'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<p><strong>Fig 2:</strong> Heatmap of correlation coffecients between variables in the 2021 World Happiness Report</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>sns.heatmap(hp21_df.corr(),annot<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Correlation between variables of 2021 World Happiness Report'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>Text(0.5, 1.0, 'Correlation between variables of 2021 World Happiness Report')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-7-output-2.png" class="img-fluid"></p>
</div>
</div>
<p><strong>Fig 3:</strong> The scatterplot below illustrates the relationship between the GDP per capita and happiness scores for each country, and uses a best-fit line to draw an association between the two variables.</p>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>sns.pairplot(data<span class="op">=</span>hp21_df, kind<span class="op">=</span><span class="st">'reg'</span>, height <span class="op">=</span> <span class="dv">6</span>,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>                  x_vars<span class="op">=</span>[<span class="st">'Happiness Score'</span>],</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>                  y_vars<span class="op">=</span>[<span class="st">'Log GDP per capita'</span>])</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Relationship between GDP per capita and Happiness'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>Text(0.5, 1.0, 'Relationship between GDP per capita and Happiness')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-8-output-2.png" class="img-fluid"></p>
</div>
</div>
<p><strong>Fig 4:</strong> This table shows the log GDP per capita of the 5 happiest countries in 2021.</p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>hp21_df[[<span class="st">"Happiness Score"</span>, <span class="st">"Log GDP per capita"</span>]].head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="14">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Happiness Score</th>
      <th>Log GDP per capita</th>
    </tr>
    <tr>
      <th>Country</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Finland</th>
      <td>7.794378</td>
      <td>10.794553</td>
    </tr>
    <tr>
      <th>Denmark</th>
      <td>7.698747</td>
      <td>10.972980</td>
    </tr>
    <tr>
      <th>Israel</th>
      <td>7.577528</td>
      <td>10.616640</td>
    </tr>
    <tr>
      <th>Iceland</th>
      <td>7.564625</td>
      <td>10.899748</td>
    </tr>
    <tr>
      <th>Sweden</th>
      <td>7.439280</td>
      <td>10.873429</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p><strong>Fig 5:</strong> This table shows the log GDP per capita of the 5 least happiest countries in 2021.</p>
<div class="cell" data-scrolled="true" data-execution_count="17">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>hp21_df[[<span class="st">"Happiness Score"</span>, <span class="st">"Log GDP per capita"</span>]].tail()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="17">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Happiness Score</th>
      <th>Log GDP per capita</th>
    </tr>
    <tr>
      <th>Country</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>India</th>
      <td>3.558254</td>
      <td>8.807804</td>
    </tr>
    <tr>
      <th>Zimbabwe</th>
      <td>3.154578</td>
      <td>8.153248</td>
    </tr>
    <tr>
      <th>Zambia</th>
      <td>3.082155</td>
      <td>8.087629</td>
    </tr>
    <tr>
      <th>Afghanistan</th>
      <td>2.436034</td>
      <td>7.695000</td>
    </tr>
    <tr>
      <th>Lebanon</th>
      <td>2.178809</td>
      <td>9.243084</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p><strong>Fig 6:</strong> The scatterplot below illustrates the relationship between life expectancy and happiness scores for each country, and uses a best-fit line to draw an association between the two variables.</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>sns.pairplot(data<span class="op">=</span>hp21_df, kind<span class="op">=</span><span class="st">'reg'</span>, height <span class="op">=</span> <span class="dv">6</span>,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                  x_vars<span class="op">=</span>[<span class="st">'Happiness Score'</span>],</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                  y_vars<span class="op">=</span>[<span class="st">'Life expectancy'</span>])</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Relationship between Life Expectancy and Happiness'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>Text(0.5, 1.0, 'Relationship between Life Expectancy and Happiness')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-11-output-2.png" class="img-fluid"></p>
</div>
</div>
<p><strong>Fig 7:</strong> This scatterplot depicts the relationship between social support and happiness scores, and uses a best-fit line to draw an association between the two variables.</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>sns.pairplot(data<span class="op">=</span>hp21_df, kind<span class="op">=</span><span class="st">'reg'</span>, height <span class="op">=</span> <span class="dv">6</span>,</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>                  x_vars<span class="op">=</span>[<span class="st">'Happiness Score'</span>],</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                  y_vars<span class="op">=</span>[<span class="st">'Social support'</span>]) </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Relationship between Social Support and Happiness'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<pre><code>Text(0.5, 1.0, 'Relationship between Social Support and Happiness')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-12-output-2.png" class="img-fluid"></p>
</div>
</div>
<p><strong>Fig 8:</strong> This scatterplot depicts the relationship between the freedom to make choices and happiness scores, and uses a best-fit line to draw an association between the two variables.</p>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>sns.pairplot(data<span class="op">=</span>hp21_df, kind<span class="op">=</span><span class="st">'reg'</span>, height <span class="op">=</span> <span class="dv">6</span>,</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                  x_vars<span class="op">=</span>[<span class="st">'Happiness Score'</span>],</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>                  y_vars<span class="op">=</span>[<span class="st">'Freedom'</span>])</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Relationship between Freedom and Happiness'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<pre><code>Text(0.5, 1.0, 'Relationship between Freedom and Happiness')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-13-output-2.png" class="img-fluid"></p>
</div>
</div>
<p><strong>Fig 9:</strong> This scatterplot depicts the relationship between perceptions of corruption and happiness scores, and uses a best-fit line to draw an association between the two variables.</p>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>sns.pairplot(data<span class="op">=</span>hp21_df, kind<span class="op">=</span><span class="st">'reg'</span>, height <span class="op">=</span> <span class="dv">6</span>,</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>                  x_vars<span class="op">=</span>[<span class="st">'Happiness Score'</span>],</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>                  y_vars<span class="op">=</span>[<span class="st">'Generosity'</span>])</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Relationship between Generosity and Happiness'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>Text(0.5, 1.0, 'Relationship between Generosity and Happiness')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-14-output-2.png" class="img-fluid"></p>
</div>
</div>
<p><strong>Fig 10:</strong> This scatterplot depicts the relationship between perceptions of corruption and happiness scores, and uses a best-fit line to draw an association between the two variables.</p>
<div class="cell" data-scrolled="true" data-execution_count="15">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>sns.pairplot(data<span class="op">=</span>hp21_df, kind<span class="op">=</span><span class="st">'reg'</span>, height <span class="op">=</span> <span class="dv">6</span>,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>                  x_vars<span class="op">=</span>[<span class="st">'Happiness Score'</span>],</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                  y_vars<span class="op">=</span>[<span class="st">'Perceptions of corruption'</span>])</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Relationship between Perceptions of Corruption and Happiness'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>Text(0.5, 1.0, 'Relationship between Perceptions of Corruption and Happiness')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-15-output-2.png" class="img-fluid"></p>
</div>
</div>
<p><strong>Fig 11:</strong> This scatterplot depicts the relationship between confidence in national government and happiness scores, and uses a best-fit line to draw an association between the two variables.</p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>sns.pairplot(data<span class="op">=</span>hp21_df, kind<span class="op">=</span><span class="st">'reg'</span>, height <span class="op">=</span> <span class="dv">6</span>,</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>                  x_vars<span class="op">=</span>[<span class="st">'Happiness Score'</span>],</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>                  y_vars<span class="op">=</span>[<span class="st">'Confidence in national government'</span>])</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Relationship between Confidence in National Government and Happiness'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>Text(0.5, 1.0, 'Relationship between Confidence in National Government and Happiness')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="FinalProject_files/figure-html/cell-16-output-2.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<section id="economy-and-happiness" class="level3">
<h3 class="anchored" data-anchor-id="economy-and-happiness">Economy and Happiness</h3>
<p>In this section, I will look at economic factors and their relationship with happiness. The key economic indicator measured in the World Happiness Report is the log GDP per capita, but I will also explore the role of life expectancy, which is significantly associated with economic factors, and their relationships with happiness.</p>
<p><strong>Relationship between GDP per capita and Happiness:</strong></p>
<p>One of the most common ways to measure a country’s economic condition is through the gross domestic product (GDP) per capita, which calculates the average economic output of each individual within a nation.</p>
<p>As can be seen from Fig 2 and 3, there is a very strong positive correlation (r = 0.79) between GDP per capita and the happiness score. This indicates that economic output and wealth of a country has a strong positive relationship with the average happiness of its citizens and that the wealthier a country, the happier the people. This is likely the case since wealthier people have more purchasing power to improve their standard of living and quality of life, are more likely to be employed, and will be more able to afford basic necessities and enjoy luxuries such as traveling, all of which will have a positive impact on happiness.</p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>hp21_df[<span class="st">'Log GDP per capita'</span>].mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>9.533486973803571</code></pre>
</div>
</div>
<div class="cell" data-scrolled="true" data-execution_count="16">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>hp21_df[<span class="st">'Log GDP per capita'</span>].median()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<pre><code>9.561124802</code></pre>
</div>
</div>
<p>Also, as seen from Fig 3 and 4, the top 5 happiest countries have a significantly higher log GDP per capita (mean = 10.83), than the mean (9.55) and median (9.56) of all countries in the report, demonstrating that the happiest countries are generally wealthier.</p>
<p>Fig 5 also illustrates that the 5 least happiest countries have a significantly lower log GDP per capita (mean = 8.4) than the mean (9.55) and median (9.56) of all countries, indicating that the least happiest countries are generally poorer.</p>
<p>However, since this (GDP per capita vs happiness) is a purely correlational relationship, no directionality or causality can be established. Also, the log GDP per capita metric does not capture wealth inequality within countries, which is an important economic indicator since countries with large wealth inequality would likely have a high GDP per capita yet low happiness scores. The insufficiency of the log GDP per capita metric in predicting happiness is best exemplified by the case of Lebanon, who despite their relatively high log GDP per capita (9.24), have the lowest happiness score (2.18), suggesting that while GDP per capita is an important indicator of happiness, there are many other factors at play.</p>
<p><strong>Relationship between Life Expectancy and Happiness:</strong></p>
<p>According to Fig 2, there is a very strong positive correlation between GDP per capita and life expectancy (r = 0.86), indicating that when countries have a higher GDP per capita, they tend to have a higher average life expectancy. This can be explained by the fact that people with higher incomes will likely have greater access to higher quality healthcare services, sanitation, nutritious food, and shelter, all of which play a part in improving overall health and life expectancy.</p>
<p>Furthermore, as seen in Fig 2 and 6, there is also a strong positive correlation between life expectancy and happiness (r = 0.73), suggesting that people would likely be happier if they lived in countries with a higher life expectancy. Again, this comes as no surprise since the aforementioned factors associated with higher life expectancy, such as healthcare and food, would likely play a role in improving quality of life and happiness overall.</p>
</section>
<section id="social-environment-and-happiness" class="level3">
<h3 class="anchored" data-anchor-id="social-environment-and-happiness">Social Environment and Happiness</h3>
<p>In this section, I will look at the relationship between one’s social environment and happiness across countries. The social environment of a country can be represented by several of the metrics in the World Happiness Report, such as social support, freedom to make choices, generosity, perceptions of corruption, and confidence in national government. These factors all play a role in shaping the social environment of a country as they can influence the level of community, social, and institutional trust within a society. Then, I will examine how these factors correlate with happiness scores to determine if there the relationship between social environment and happiness.</p>
<p><strong>Relationship between Social Support and Happiness:</strong></p>
<p>Social support, as operationalized in the World Happiness Report, refers to having someone to count on in times of trouble. Having a strong social support system and having frequent interactions with them has been found to have positive effects on creating “feelings of love, care, self-esteem, and value”, all of which have direct implications on instilling feelings of happiness (Moeini et al., 2018). This is supported by the data, as observed in Fig 2 and 7, where there is a strong positive correlation between social support and happiness (r = 0.72), which means that the greater the social support reported, the higher the happiness levels.</p>
<p><strong>Relationship between Freedom and Happiness:</strong></p>
<p>Freedom is measured by the self-reported level of freedom to choose what they can do with their lives. As seen in Fig 2 and 8, there is a strong positive correlation between freedom and happiness (r = 0.61), which means that the greater the freedom reported, the happier the people. When people have more freedom, they are more able to live life the way they want, which is likely to lead to a happier and more fulfilling life. Furthermore, research has found that humans have an innate need for freedom, with ‘autonomy’ being a primary psychological need (Rahman &amp; Veenhoven, 2017). As such, if people perceived themselves to have low levels of freedom, it would almost be as if a primary need was taken away from them, and that would likely have adverse effects on happiness.</p>
<p><strong>Relationship between Generosity and Happiness:</strong></p>
<p>Generosity is operationalized by the number of times people have donated to charity in a month. Country with higher levels of generosity would likely have a more inclusive and trusting society where people value the needs of others. In fact, studies on generosity and happiness have found that people who give money to charity or help others were more likely to be happier than those who did not (Aknin et al., 2013). However, as seen from Fig 2 and 4, generosity only has a weak positive correlation with happiness (r = 0.14), which means that societies with higher levels of generosity do not necessarily have higher happiness scores, going against literature and what one would expect.</p>
<p><strong>Relationship between Institutional Trust and Happiness:</strong></p>
<p>Institutional trust, based on the data provided, can be measured by perceptions of corruption and confidence in national government, such as the legal system and the police. Countries with higher levels of institutional trust more likely provide its citizens with a greater sense of security and stability, which can improve happiness. However, this is not consistently represented in the data gathered.</p>
<p>As seen from Fig 2 and 10, there is a moderate negative correlation between perceptions of corruption and happiness (r = -0.45), which means that the lesser the perceived level of corruption in governments and businesses, there is generally higher levels of happiness. When perceived corruption is high, people have lower trust in institutions, which has further socioeconomic effects such as discouraging investment and political participation, which will have negative effects on well-being.</p>
<p>On the other hand, as displayed in Fig 2 and 11, there is no correlation between confidence in national government and happiness (r= -0.01), which means that levels of confidence in national government have no effect on happiness whatsoever. This is surprising as one would expect that with higher levels of confidence in national government, there would be greater trust in institutions’ ability to address citizens’ needs and tackling societal issues, which would lead to higher happiness. Also, past studies have found confidence in national government to be positively associated wiht happiness (Luhmann et al., 2012). As such, further exploration into the data has to be done to understand the reason for this aberration, such as errors in the dataset.</p>
</section>
<section id="implications" class="level3">
<h3 class="anchored" data-anchor-id="implications">Implications</h3>
<p>Overall, we can see that economic factors such as GDP per capita and life expectancy, as well as social factors such as social support and freedom have a strong positive correlation on happiness. On a governmental level, this data lays out a figurative blueprint for how they can develop policies to create a happier population, such as by investing in more communal spaces to improve social support, improving healthcare services to lengthen average life expectancy, or allowing for greater freedom of choice in society. Meanwhile, individuals are also able to glean insights from this data and analysis, gaining a stronger awareness of factors that contribute to their happiness, and adjust their lifestyles accordingly to optimize for greater well-being. For example, people can start prioritizing quality social interactions and actively engaging with communities to create a greater social support system, and boost their happiness.</p>
</section>
</section>
<section id="citations" class="level2">
<h2 class="anchored" data-anchor-id="citations">Citations</h2>
<ol type="1">
<li><p>Jahaidul Islam. (2023). <i>World Happiness Report 2005-2021</i> [Data set]. Kaggle. https://doi.org/10.34740/KAGGLE/DS/2927598</p></li>
<li><p>Moeini, B., Barati, M., Farhadian, M., &amp; Ara, M. H. (2018). The Association between Social Support and Happiness among Elderly in Iran. Korean journal of family medicine, 39(4), 260–265. https://doi.org/10.4082/kjfm.17.0121</p></li>
<li><p>Abdur Rahman, A., &amp; Veenhoven, R. (2017). Freedom and happiness in nations: A research synthesis. Applied Research in Quality of Life, 13(2), 435–456. https://doi.org/10.1007/s11482-017-9543-6</p></li>
<li><p>Aknin, L. B., Dunn, E. W., &amp; Norton, M. I. (2013). Happiness runs in a circular motion: Evidence for a positive feedback loop between prosocial spending and happiness. Journal of Happiness Studies, 14(6), 1629-1641.</p></li>
<li><p>Luhmann, M., Hofmann, W., Eid, M., &amp; Lucas, R. E. (2012). Subjective well-being and adaptation to life events: A meta-analysis. Journal of Personality and Social Psychology, 102(3), 592-615. https://doi.org/10.1037/a0025948</p></li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>